# Netscape HTTP Cookie File
# http://curl.haxx.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

panel.myownfreehost.net	FALSE	/	FALSE	0	PHPSESSID	gh2mc792ndihdb793bts0cnet2
panel.myownfreehost.net	FALSE	/	FALSE	1589963590	cookrole	administrator
